### ISSUE TITLE
[FakeMod] Commands list 

### ISSUE THREAD

**Issue by JeffJrShim** [JeffJrShim/noa-cogs#2]
Commands and so on:
- [x] Bam equivalent to bam
- [ ] moot equivalent to mute
- [ ] warm equivalent to warn
- [ ] keck equivalent to kick

**Comment by JeffJrShim** [comment]
This will be started after my exams. I still have revisions to do.

**Comment by JeffJrShim** [comment]
Bam done.

**Comment by guacaplushy** [comment]
Added keck [untested]

**Comment by guacaplushy** [comment]
Added moot [untested]

**Comment by guacaplushy** [comment]
All are done but added ones are untested
